macro(enable_warnings)
    if (MSVC)
        add_compile_options(/W4 /permissive- /wd4324 /WX)
    else ()
        add_compile_options(-Wall -Wextra -Wpedantic -Wshadow -Wconversion -Werror)
    endif ()
endmacro()

macro(enable_sanitizer)
    if (MSVC)
        add_compile_options(/fsanitize=address)
        add_link_options(/fsanitize=address)
    else ()
        add_compile_options(-fsanitize=address -fsanitize=undefined)
        add_link_options(-fsanitize=address -fsanitize=undefined)
    endif ()
endmacro()

macro(enable_coverage)
    if (NOT MSVC)
        add_compile_options(-fprofile-arcs -ftest-coverage)
        add_link_options(-fprofile-arcs -ftest-coverage)
    endif ()
endmacro()