macro(enable_warnings)
    message(STATUS "Utilities: Enabling warnings")
    if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        add_compile_options(/W4 /permissive- /wd4324 /WX)
    else ()
        add_compile_options(-Wall -Wextra -Wpedantic -Wshadow -Wconversion -Werror)
    endif ()
endmacro()

macro(enable_sanitizer)
    message(STATUS "Utilities: Enabling address sanitizer")
    if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        add_compile_options(/fsanitize=address)
        add_link_options(/fsanitize=address)
    else ()
        add_compile_options(-fsanitize=address -fsanitize=undefined)
        add_link_options(-fsanitize=address -fsanitize=undefined)
    endif ()
endmacro()

macro(enable_coverage)
    message(STATUS "Utilities: Enabling test coverage")
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        add_compile_options(-fprofile-instr-generate -fcoverage-mapping)
        add_link_options(-fprofile-instr-generate -fcoverage-mapping)
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        add_compile_options(-fprofile-arcs -ftest-coverage)
        add_link_options(-fprofile-arcs -ftest-coverage)
    endif ()
endmacro()